// Generated by gencpp from file exercise1/Greeting.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_GREETING_H
#define EXERCISE1_MESSAGE_GREETING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise1
{
template <class ContainerAllocator>
struct Greeting_
{
  typedef Greeting_<ContainerAllocator> Type;

  Greeting_()
    : content()  {
    }
  Greeting_(const ContainerAllocator& _alloc)
    : content(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _content_type;
  _content_type content;





  typedef boost::shared_ptr< ::exercise1::Greeting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise1::Greeting_<ContainerAllocator> const> ConstPtr;

}; // struct Greeting_

typedef ::exercise1::Greeting_<std::allocator<void> > Greeting;

typedef boost::shared_ptr< ::exercise1::Greeting > GreetingPtr;
typedef boost::shared_ptr< ::exercise1::Greeting const> GreetingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise1::Greeting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise1::Greeting_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise1::Greeting_<ContainerAllocator1> & lhs, const ::exercise1::Greeting_<ContainerAllocator2> & rhs)
{
  return lhs.content == rhs.content;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise1::Greeting_<ContainerAllocator1> & lhs, const ::exercise1::Greeting_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise1::Greeting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise1::Greeting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise1::Greeting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise1::Greeting_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise1::Greeting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise1::Greeting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise1::Greeting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e84951ee6d0addf437bfddd5b19734";
  }

  static const char* value(const ::exercise1::Greeting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e84951ee6d0addULL;
  static const uint64_t static_value2 = 0xf437bfddd5b19734ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise1::Greeting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise1/Greeting";
  }

  static const char* value(const ::exercise1::Greeting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise1::Greeting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string content\n"
"\n"
;
  }

  static const char* value(const ::exercise1::Greeting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise1::Greeting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Greeting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise1::Greeting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise1::Greeting_<ContainerAllocator>& v)
  {
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.content);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE1_MESSAGE_GREETING_H
