// Generated by gencpp from file exercise1/Reverse.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_REVERSE_H
#define EXERCISE1_MESSAGE_REVERSE_H

#include <ros/service_traits.h>


#include <exercise1/ReverseRequest.h>
#include <exercise1/ReverseResponse.h>


namespace exercise1
{

struct Reverse
{

typedef ReverseRequest Request;
typedef ReverseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reverse
} // namespace exercise1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise1::Reverse > {
  static const char* value()
  {
    return "a6ae0dfa99b6e1c22e0f4dd5d3d7311b";
  }

  static const char* value(const ::exercise1::Reverse&) { return value(); }
};

template<>
struct DataType< ::exercise1::Reverse > {
  static const char* value()
  {
    return "exercise1/Reverse";
  }

  static const char* value(const ::exercise1::Reverse&) { return value(); }
};


// service_traits::MD5Sum< ::exercise1::ReverseRequest> should match
// service_traits::MD5Sum< ::exercise1::Reverse >
template<>
struct MD5Sum< ::exercise1::ReverseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::Reverse >::value();
  }
  static const char* value(const ::exercise1::ReverseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::ReverseRequest> should match
// service_traits::DataType< ::exercise1::Reverse >
template<>
struct DataType< ::exercise1::ReverseRequest>
{
  static const char* value()
  {
    return DataType< ::exercise1::Reverse >::value();
  }
  static const char* value(const ::exercise1::ReverseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise1::ReverseResponse> should match
// service_traits::MD5Sum< ::exercise1::Reverse >
template<>
struct MD5Sum< ::exercise1::ReverseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::Reverse >::value();
  }
  static const char* value(const ::exercise1::ReverseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::ReverseResponse> should match
// service_traits::DataType< ::exercise1::Reverse >
template<>
struct DataType< ::exercise1::ReverseResponse>
{
  static const char* value()
  {
    return DataType< ::exercise1::Reverse >::value();
  }
  static const char* value(const ::exercise1::ReverseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE1_MESSAGE_REVERSE_H
