// Generated by gencpp from file exercise1/ReverseResponse.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_REVERSERESPONSE_H
#define EXERCISE1_MESSAGE_REVERSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise1
{
template <class ContainerAllocator>
struct ReverseResponse_
{
  typedef ReverseResponse_<ContainerAllocator> Type;

  ReverseResponse_()
    : comment()  {
    }
  ReverseResponse_(const ContainerAllocator& _alloc)
    : comment(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _comment_type;
  _comment_type comment;





  typedef boost::shared_ptr< ::exercise1::ReverseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise1::ReverseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReverseResponse_

typedef ::exercise1::ReverseResponse_<std::allocator<void> > ReverseResponse;

typedef boost::shared_ptr< ::exercise1::ReverseResponse > ReverseResponsePtr;
typedef boost::shared_ptr< ::exercise1::ReverseResponse const> ReverseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise1::ReverseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise1::ReverseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise1::ReverseResponse_<ContainerAllocator1> & lhs, const ::exercise1::ReverseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.comment == rhs.comment;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise1::ReverseResponse_<ContainerAllocator1> & lhs, const ::exercise1::ReverseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise1::ReverseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise1::ReverseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise1::ReverseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise1::ReverseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise1::ReverseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise1::ReverseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise1::ReverseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83609817d68993e8cc8571226bf4197d";
  }

  static const char* value(const ::exercise1::ReverseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83609817d68993e8ULL;
  static const uint64_t static_value2 = 0xcc8571226bf4197dULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise1::ReverseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise1/ReverseResponse";
  }

  static const char* value(const ::exercise1::ReverseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise1::ReverseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response constants\n"
"#uint32 SECRET=123456\n"
"#response fields\n"
"#another_pkg/YetAnotherMessage val\n"
"#CustomMessageDefinedInThisPackage value\n"
"#int32 result\n"
"string comment\n"
;
  }

  static const char* value(const ::exercise1::ReverseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise1::ReverseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.comment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReverseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise1::ReverseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise1::ReverseResponse_<ContainerAllocator>& v)
  {
    s << indent << "comment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.comment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE1_MESSAGE_REVERSERESPONSE_H
